const exams = [
  {
    id: 1,
    title: 'Exam 1',
    description: 'Exam 1 description',
    time: 10, // minutes
    questions: [
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 2,
        title: 'Question 2',
        description: 'Question 2 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 10,
        title: 'Question 10',
        description: 'Question 10 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'c',
      },
    ],
  },
  {
    id: 2,
    title: 'Exam 2',
    description: 'Exam 2 description',
    time: 2, // minutes
    questions: [
      {
        id: 1,
        title: 'Question 1',
        description: 'Question 1 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'a',
      },
      {
        id: 2,
        title: 'Question 2',
        description: 'Question 2 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
        correctAnswer: 'b',
      },
      {
        id: 10,
        title: 'Question 10',
        description: 'Question 10 description',
        answers: {
          a: 'Answer 1',
          b: 'Answer 2',
          c: 'Answer 3',
          d: 'Answer 4',
        },
      },
    ],
  },
];
export default exams;
